### ISSUE TITLE
can't install on centos7 with 5.0.4-1.el7.elrepo.x86_64

### ISSUE THREAD

**Issue by kmsluxc** [LiveChief/wireguard-install#11]
#bash wireguard-server.sh
Tell me a name for the client config file. Use one word only, no special characters.
Client name: sfwsa
wireguard-server.sh: line 218: wg: command not found
wireguard-server.sh: line 219: wg: command not found
wireguard-server.sh: line 226: -4: substring expression < 0

**Comment by LiveChief** [comment]
@kmsluxc give me 24 hours and ill fix it.

**Comment by LiveChief** [comment]
Its been fixed, try it now.
