### ISSUE TITLE
port 443

### ISSUE THREAD

**Issue by malikshi** [LiveChief/wireguard-install#12]
most isp there can't connect wireguard port 443 idk why.
please remove upgrade dist sometime for low spec vps bit annoying if failed upgrade

**Comment by LiveChief** [comment]
works on port 443 fine for me.
just fork it and remove it, most people who are going to be using this script will have normal decent vps

**Comment by malikshi** [comment]
> works on port 443 fine for me.
> just fork it and remove it, most people who are going to be using this script will have normal decent vps

there sometimes i need reboot/restart service everytime client can't connect. is it problem from wireguard itself?

**Comment by LiveChief** [comment]
i haven't faced any issues like this, try a digitalocean droplet or a vultr droplet and maybe the connection could be better

**Comment by malikshi** [comment]
> i haven't faced any issues like this, try a digitalocean droplet or a vultr droplet and maybe the connection could be better

sorry i think my vps from ovh got blocked, i just know it after installing on vultr bcz not blocked

**Comment by LiveChief** [comment]
oh okay :)
