### ISSUE TITLE
To Do.

### ISSUE THREAD

**Issue by LiveChief** [LiveChief/wireguard-install#14]
1. DONE.
2. Add Feature To Remove Users.
3. ReGenerate User QR Codes.
4. Unbound.
5. Add Function To Remove Unbound
6. Add Function To Remove WireGuard
7. DONE.

**Comment by malikshi** [comment]
@LiveChief please added this for remove peer, its based your script.
client still can connect but their wont got traffic internet because the peer already deleted. sorry, i cant pull request through Github because i scripting for multi vpn/tunneling service with one script.

> #!/bin/bash
> #m.me/ibnumalik.al
> ### Server is installed, add a new client
> 	WG_CONFIG="/etc/wireguard/wg0.conf"
>     CLIENT_NAME="$1"
>     if [ "$CLIENT_NAME" == "" ]; then
>         echo "Tell me a name for the client config file. Use one word only, no special characters."
>         read -p "Client name: " -e CLIENT_NAME
>     fi
> 
> 	CURRENTLINE=$( grep -n "$CLIENT_NAME" $WG_CONFIG | awk -F  ":" '{print $1}' )
> 	ENDLINE=$(( $CURRENTLINE+3 ))
> 	ENDPEER=$(( $CURRENTLINE+2 ))
> 	PUBKEY=$( head -n $ENDPEER $WG_CONFIG | tail -1 | awk '{print $3}')
> 	wg set wg0 peer $PUBKEY remove
> 	sed -i "$CURRENTLINE,${ENDLINE}d" $WG_CONFIG

**Comment by LiveChief** [comment]
testing it locally, and it will be added to the script with unbound by the end of the week.

**Comment by LiveChief** [comment]
what do u think about this code?


```
function install_unbound () {	
            apt-get install unbound unbound-host -y	
            # Configuration	
            wget /var/lib/unbound/root.hints -O https://www.internic.net/domain/named.cache	
            cp /usr/share/dns/root.key /var/lib/unbound/	
            systemctl disable systemd-resolved.service	
            service systemd-resolved stop	
echo "" > /etc/unbound/unbound.conf	
echo "server:	
  num-threads: 4	
  do-ip6: no  # Disable ip6 for Azure	
  #Enable logs	
  verbosity: 1	
  #list of Root DNS Server	
  root-hints: "/var/lib/unbound/root.hints"	
  #Use the root servers key for DNSSEC	
  auto-trust-anchor-file: "/var/lib/unbound/root.key"	
  #Respond to DNS requests on all interfaces	
  interface: 0.0.0.0	
  max-udp-size: 3072	
  #Authorized IPs to access the DNS Server	
  access-control: 0.0.0.0/0                 refuse	
  access-control: 127.0.0.1                 allow	
  access-control: 10.8.0.0/24               allow	
  #not allowed to be returned for public internet  names	
  private-address: 10.8.0.0/24	
  # Hide DNS Server info	
  hide-identity: yes	
  hide-version: yes	
  #Limit DNS Fraud and use DNSSEC	
  harden-glue: yes	
  harden-dnssec-stripped: yes	
  harden-referral-path: yes	
  #Add an unwanted reply threshold to clean the cache and avoid when possible a DNS Poisoning	
  unwanted-reply-threshold: 10000000	
  #Have the validator print validation failures to the log.	
  val-log-level: 1	
  #Minimum lifetime of cache entries in seconds	
  cache-min-ttl: 1800	
  #Maximum lifetime of cached entries	
  cache-max-ttl: 14400	
  prefetch: yes	
  prefetch-key: yes" > /etc/unbound/unbound.conf	
chown -R unbound:unbound /var/lib/unbound	
systemctl enable unbound	
service unbound restart	
iptables -A INPUT -s 10.0.0.0/24 -p udp -m udp --dport 53 -m conntrack --ctstate NEW -j ACCEPT	
}
```

**Comment by LiveChief** [comment]
```
apt-get install unbound unbound-host -y

cp /usr/share/dns/root.key /var/lib/unbound/

systemctl disable systemd-resolved.service

service systemd-resolved stop

echo "" > /etc/unbound/unbound.conf	

echo "server:
  num-threads: 4	
  do-ip6: no  # Disable ip6 for Azure	
  #Enable logs	
  verbosity: 1	
  #list of Root DNS Server	
  root-hints: "/var/lib/unbound/root.hints"	
  #Use the root servers key for DNSSEC	
  auto-trust-anchor-file: "/var/lib/unbound/root.key"	
  #Respond to DNS requests on all interfaces	
  interface: 0.0.0.0	
  max-udp-size: 3072	
  #Authorized IPs to access the DNS Server	
  access-control: 0.0.0.0/0                 refuse	
  access-control: 127.0.0.1                 allow	
  access-control: 10.8.0.0/24               allow	
  #not allowed to be returned for public internet  names	
  private-address: 10.8.0.0/24	
  # Hide DNS Server info	
  hide-identity: yes	
  hide-version: yes	
  #Limit DNS Fraud and use DNSSEC	
  harden-glue: yes	
  harden-dnssec-stripped: yes	
  harden-referral-path: yes	
  #Add an unwanted reply threshold to clean the cache and avoid when possible a DNS Poisoning	
  unwanted-reply-threshold: 10000000	
  #Have the validator print validation failures to the log.	
  val-log-level: 1	
  #Minimum lifetime of cache entries in seconds	
  cache-min-ttl: 1800	
  #Maximum lifetime of cached entries	
  cache-max-ttl: 14400	
  prefetch: yes	
  prefetch-key: yes" > /etc/unbound/unbound.conf

chown -R unbound:unbound /var/lib/unbound

systemctl enable unbound

service unbound restart

chattr -i /etc/resolv.conf

sed -i "s|nameserver|#nameserver|" /etc/resolv.conf

sed -i "s|search|#search|" /etc/resolv.conf

echo "nameserver 127.0.0.1" >> /etc/resolv.conf

chattr +i /etc/resolv.conf

iptables -A INPUT -s 10.8.0.0/24 -p udp -m udp --dport 53 -m conntrack --ctstate NEW -j ACCEPT	

```

**Comment by LiveChief** [comment]
@malikshi 
can u help me with this...
https://github.com/LiveChief/wireguard-install/pull/19

thanks.

**Comment by LiveChief** [comment]
> @LiveChief please added this for remove peer, its based your script.
> client still can connect but they wont got traffic internet because the peer already deleted. sorry, i cant pull request through Github because i scripting for multi vpn/tunneling service with one script.
> 
> > #!/bin/bash
> > #m.me/ibnumalik.al
> > #Server is installed, add a new client
> > WG_CONFIG="/etc/wireguard/wg0.conf"
> > CLIENT_NAME="$1"
> > if [ "$CLIENT_NAME" == "" ]; then
> > echo "Tell me a name for the client config file. Use one word only, no special characters."
> > read -p "Client name: " -e CLIENT_NAME
> > fi
> > CURRENTLINE=$( grep -n "$CLIENT_NAME" $WG_CONFIG | awk -F  ":" '{print $1}' )
> > ENDLINE=$(( $CURRENTLINE+3 ))
> > ENDPEER=$(( $CURRENTLINE+2 ))
> > PUBKEY=$( head -n $ENDPEER $WG_CONFIG | tail -1 | awk '{print $3}')
> > wg set wg0 peer $PUBKEY remove
> > sed -i "$CURRENTLINE,${ENDLINE}d" $WG_CONFIG

make a pull request when your free.

**Comment by LiveChief** [comment]
https://gist.githubusercontent.com/LiveChief/c16562cc1bf83ab14da8096c8fdaca96/raw/a38992675754007377e8d4e8eb00f52b7a022d7e/unbound.MD

**Comment by LiveChief** [comment]
`PRESHARED_KEY=$( wg genpsk )`
`PresharedKey = $PRESHARED_KEY
`

**Comment by LiveChief** [comment]
<script src="https://gist.github.com/LiveChief/c16562cc1bf83ab14da8096c8fdaca96.js"></script>

**Comment by LiveChief** [comment]
2604:a880:400:d1::b4c:2001
