### ISSUE TITLE
Connected, am able to ping IPs and URLs. But no connection to internet otherwise

### ISSUE THREAD

**Issue by UNlDAN** [LiveChief/wireguard-install#16]
Tested on AWS, GCP and a Hyper-V Ubuntu 16.04 VM.

**Comment by UNlDAN** [comment]
Firewall is set to allow EVERYTHING in and out

**Comment by UNlDAN** [comment]
Issue fixed itself. Needed to do 3 reboots on each machine.

**Comment by LiveChief** [comment]
wow.
