### ISSUE TITLE
OSX Wireguard client stuck on 

### ISSUE THREAD

**Issue by Leopere** [LiveChief/wireguard-install#49]
## OSX Client Version 1.0.3 Sending handshare initiation.
This times out over and over.
```SYSLOG
2019-06-05 12:50:17.202 [NET] peer(5VSZ…j2iE) - Sending handshake initiation
```
Doesn't look like any data is coming back from the remote server.

## Screenshot

![Screenshot](https://i.imgur.com/8D2EiMx.jpg)

**Comment by LiveChief** [comment]
do u have a firewall or something on the server? 

or like cloud firewall or something?

**Comment by Leopere** [comment]
Okay so yes the wifi I was on was blocking WireGuard's responses.  I made an issue in reference to wanting "stealth mode" suggestions in the Q&A portion of the installer #50 I think this would be pertinent. 

That error really isn't documented anywhere and doesn't seem indicative of anything useful so for future netizens I'll close this and mention that its a routing issue in the network between my "client" and the "server".
