### ISSUE TITLE
FeatureRequest: Stealth mode presets.

### ISSUE THREAD

**Issue by Leopere** [LiveChief/wireguard-install#50]
## Concept

Just thinking that one of the things that could be recommended in the Q&A portion of the installation script is adding parentheses that are recommended for stealth operation.

## Example 

```BASH
Listen Port:
1) Port 51463/udp (recommended)
2) Port 443/tcp (stealth)
3) Port 53/udp (stealth)
```

**Comment by LiveChief** [comment]
443/tcp for what ??

Wireguard is UDP only 


Sorry I am in school and will take a look at all your issues and fix all of them by tonight

**Comment by LiveChief** [comment]
@Leopere wanna make a pull or want me to do it?

i don't see TCP being used cause wireguard is udp only but the other thing is cool.

**Comment by Leopere** [comment]
I don't remember where I read it but someone suggested that WireGuard could do TCP in a pinch but I think you're right that it doesn't do it at all.

I think you're more the expert here so I'll let you decide what to suggest but as my issue #49 it's definitely obvious that I'm going to end up needing to find another way around this strangely configured public wifi AP

**Comment by LiveChief** [comment]
@Leopere
https://tunsafe.com/user-guide/tcp

**Comment by Leopere** [comment]
Sounds atrocious UDP should likely work most of the time.  The only problem I see is what ports to suggest that likely won't be blocked.  I do know that Skypes port range is frequently available however I don't recall if it's TCP or UDP.  I used to use it before via the Angristan/openvpn-install and this specific AP in the past.

**Comment by Leopere** [comment]
Yea so the attempt was made, okay well its something that would be nice but unfortunately, I only know of it as a possibility and it would be a fairly significant upgrade to privacy.

The only other option that I could imagine is [DNSCRYPT](https://dnscrypt.info) if it's not too painful.  the idea is to encrypt the DNS queries before they leave the server.  So as to avoid leaking unnecessary metadata.  I realize the IP and domain is still in the http packet header if I recall correctly but reducing the number of vectors for metadata collection is always a plus.

**Comment by Leopere** [comment]
https://support.skype.com/en/faq/FA148/which-ports-need-to-be-open-to-use-skype-on-desktop might be a good set of ranges to masquerade as.  

https://support.apple.com/en-us/HT202944 
https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

**Comment by LiveChief** [comment]
pull.

**Comment by Leopere** [comment]
I'm cool with making some suggestions via PR but I need to know what ports will function here.  Unfortunately, there's no uninstall and reinstall feature in this script yet.

**Comment by Leopere** [comment]
Okay, I've tested skype ports on this network and it's working fine.  So now we just need to find other popular apps that people won't be happy without in public network settings and see what we can do with adding them.

The benefit of Skype is that it's a port range between the following ranges.
```
3478-3481/UDP
50000-60000/UDP
```

Further testing still required but this works perfectly in my case.

**Comment by Leopere** [comment]
WhatsApp also uses these UDP ports.
```
Updated On Oct 12, 2017

TCP Ports; 80, 443, 4244, 5222, 5223, 5228, 5242, 50318, 59234

UDP Ports: 34784, 45395, 50318, 59234
```

**Comment by Leopere** [comment]
Nevermind this is something I don't want to encourage.
