### ISSUE TITLE
Feature Request: Unbound configured for DNS over TLS

### ISSUE THREAD

**Issue by Leopere** [LiveChief/wireguard-install#51]
One of the things that bother me immensely is leaking data via means of DNS queries.  Since Unbound is what PiHole documentation alludes to being the DNS relay that is equipped for DNS over TLS/HTTPS

**Comment by LiveChief** [comment]
this...

https://dnsprivacy.org/wiki/display/DP/Using+Unbound+as+a+DNS+Privacy+server

???

**Comment by Leopere** [comment]
Hmm no that's the other side of the equation it sounded like Unbound could act as a DNS over TLS/HTTPS client/relay.

**Comment by Leopere** [comment]
My apologies that guide is set up the way it should be.  However, you wouldn't need to give it any certificates within the WireGuard side as that's already encrypted.

**Comment by LiveChief** [comment]
ok.

@Leopere i think this is what your talking about.

check this out
https://github.com/LiveChief/wireguard-install/pull/24

**Comment by Leopere** [comment]
The other option is [DNSCRYPT](https://dnscrypt.info/) if that is an option but it's not a standard and I'm not really sure when the data stops being encrypted up the chain.

Good luck with whatever happens for you at Microsoft!

**Comment by LiveChief** [comment]
```
  tls-service-key: "/usr/local/unbound/etc/dns_over_tls.key"
  tls-service-pem: "/usr/local/unbound/etc/dns_over_tls.pem"
  tls-port: 853
  interface: 127.0.0.1@853
  interface: ::1@853
```

**Comment by Leopere** [comment]
Also, [calomel.org](https://calomel.org/unbound_dns.html) tends to have pretty good insights on how to do security and privacy on a pretty high thorough level.

**Comment by LiveChief** [comment]
they have dns over tls upstream but not down stream so lets add downstream..

**Comment by Leopere** [comment]
Your local computer  (wireguard "client") sends vanilla DNS query via Wireguard > internet > wireguard "server" including DNS Unbound > upstream recursive [DoH](https://en.wikipedia.org/wiki/DNS_over_HTTPS) server.

**Comment by Leopere** [comment]
There's likely no reason to send a query from your local PC to Unbound over WireGuard so long as we can get Unbound to relay from a remote recursive server that supports DoH it might be possible and should be how it's done.

**Comment by LiveChief** [comment]
u mean this?/

https://github.com/LiveChief/wireguard-install/pull/52

**Comment by Leopere** [comment]
That I do, I imagine that'll close this once it's merged.

**Comment by LiveChief** [comment]
Wrote the code and got on a train to mracosoft so I'll test it when I get home or from there and I'll merge that once i deem it to be stable.

**Comment by LiveChief** [comment]
i am back and i actually spoke with a bunch of people and seems like they will be helping me :)

cause a little bitch doesn't want to make a pull..

**Comment by Leopere** [comment]
lol, Jesus, that escalated.  If you want help I can poke at it perhaps.  You just know more about how WG works far more reliably than I do.

Good to hear there's, potential contributors, you seemed to have it under control.

**Comment by LiveChief** [comment]
@Leopere don't worry about it, ill fix it and ill make the merge by tonight.

**Comment by Leopere** [comment]
I'm not in a rush anyways just wanted to put idea fuel into the crucible here.  If you want someone to review/tweak the PR I'm definitely willing I just have about 10 other things I need to focus on right now.

**Comment by Leopere** [comment]
We should start a discord or something for all of this.

**Comment by LiveChief** [comment]
@Leopere what's your discord?

**Comment by Leopere** [comment]
Joined

**Comment by Leopere** [comment]
#60 completes this feature, now the default functionality is that when Unbound is installed your client will send its DNS queries over the WireGuard tunnel to Unbound on the VPS which will then send obtain DNS records via DoH from upstream recursive servers from a predetermined list of DNS recursive servers supported by this script.
