### ISSUE TITLE
FeatureRequest: Ability to provide answers by means of environment variables.

### ISSUE THREAD

**Issue by Leopere** [LiveChief/wireguard-install#54]
When you ask the user questions these things should also be answerable via environment variables for those of us who just want to pass a set of things into the thing and have the thing all in a headless thing.

**Comment by LiveChief** [comment]
This is literally gay, not adding this now.

**Comment by Leopere** [comment]
It wouldn't be too painful could just put a check into a function and call it before you ask the user questions.  It would be useful for people wanting to use this script for insta deployment of these things via cloud-inits and things like that.

**Comment by LiveChief** [comment]
Ok

**Comment by Leopere** [comment]
#60 fixes this technically, however, it's not documented or tested and may not cover all questions available to the end user in its the current state.
