### ISSUE TITLE
/usr/sbin/ip6tables-restore error

### ISSUE THREAD

**Issue by Dedi-Data** [LiveChief/wireguard-install#73]
**Describe the bug**

I got this error when I was installing on CentOS 7:

Error: COMMAND_FAILED: '/usr/sbin/ip6tables-restore -w -n' failed: ip6tables-restore v1.4.21: option "--to" requires an argument
Error occurred at line: 2
Try `ip6tables-restore -h' or 'ip6tables-restore --help' for more information.

However everything working great,
Thank you for maintenance

**Comment by Dedi-Data** [comment]
https://github.com/LiveChief/wireguard-install/pull/74

**Comment by LiveChief** [comment]
Fixed.
