### ISSUE TITLE
firewalld wrong rules

### ISSUE THREAD

**Issue by Dedi-Data** [LiveChief/wireguard-install#77]
**Describe the bug**

I found that there are problems with firewalld rules:
`firewall-cmd --direct --add-rule ipv4 nat POSTROUTING 0 -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to 10.8.0.0/24
`
**Error: COMMAND_FAILED: '/usr/sbin/iptables-restore -w -n' failed: iptables-restore v1.4.21: Bad IP address "10.8.0.0/24"**

**Error occurred at line: 2**
**Try `iptables-restore -h' or 'iptables-restore --help' for more information.**

**Comment by Dedi-Data** [comment]
Sorry that was my mistake

**Comment by LiveChief** [comment]
@Dedi-Data what???

i don't think i have that on my script...
